UKR-195 Categories and UKR-196 Subcategories
awe-der/aweder-core pull request #43
Opened 2020-07-11 16:04 UTC by jump24-luke

2020-07-13 06:23 UTC, AlexJump24 commented on database/migrations/2020_07_11_134535_rename_category_id_to_order_on_categories_table.php
> +        Schema::table('categories', function (Blueprint $table) {
I see this is still in draft but while I am having a quick look I'll note, we need to add checks around all of the new migrations to check tables/columns exist etc. 

- [ ] Add migrations checks

2020-08-20 10:19 UTC, dannewnsjump24 requested changes
its mainly around the test names we seem to have changed the naming conventions here, can we double check the rest and make sure that these new ones match what we already have in the codebase.

2020-08-20 10:19 UTC, dannewnsjump24 commented on tests/Unit/Repository/CategoriesRepositoryTest.php
> +    public function createCategoriesWithValidData(): void
ok so this looks to have moved away from the standard we've used on the project up to now with regards to camel case and snake case. if we use `_` throughout the rest can we rename these to be the same

2020-08-21 06:15 UTC, dannewnsjump24 approved these changes

2020-08-21 06:24 UTC, AlexJump24 approved these changes

2020-08-21 08:03 UTC, merged