UKR 284 Table Order creation endpoint writes out correctly
awe-der/aweder-core pull request #88
Opened 2020-08-27 16:00 UTC by SecondeJK

2020-08-28 06:28 UTC, dannewnsjump24 requested changes

2020-08-28 06:28 UTC, dannewnsjump24 commented on app/Http/Requests/Api/Order/ApiCreateOrderRequest.php
> +            'table_number' => ['string', 'nullable'],
We could add required if here so that if is table service is true then table number is required. this would then mean we can bring out some of the checks in the controllers perhaps?

2020-08-28 06:28 UTC, dannewnsjump24 commented on app/Http/Requests/Api/Order/ApiCreateOrderRequest.php
> +            'table_number' => ['string', 'nullable'],
- [ ] Add Validation here to check if table_number is present when `is_table_service` is set

2020-09-01 06:55 UTC, AlexJump24 approved these changes

2020-09-01 06:59 UTC, dannewnsjump24 commented on app/Http/Controllers/Api/Order/CreateController.php
> +        if (isset($payload['is_table_service'])) {
Can you just check your PHPStorm here as i'm surprised its not flagging this up as being able to combine this into a one line check.

2020-09-01 07:00 UTC, dannewnsjump24 approved these changes
Looks good, I did ask one question around the CreateController just to check your PHPStorm settings to see if its flagging anything up

2020-11-17 11:44 UTC, merged