Feature/ukr 297 add preferences to inventory item storefront
awe-der/aweder-core pull request #98
Opened 2020-11-17 15:08 UTC by SecondeJK

2020-11-17 15:25 UTC, dannewnsjump24 requested changes

2020-11-17 15:25 UTC, dannewnsjump24 commented on resources/views/admin/inventory/index.blade.php
> +                                                        <span class="icon icon--add selected">
wouldnt it be better to just add the selected class as part of if else instead of having two sets of HTML here?

2020-11-17 15:25 UTC, dannewnsjump24 commented on resources/views/admin/inventory/index.blade.php
> +                                                        <span class="icon icon--add selected">
- [ ] move if else to just class based

2020-11-17 15:25 UTC, dannewnsjump24 commented on resources/views/admin/inventory/index.blade.php
> +                                                    @if(!$item->is_vegetarian)
Clean up the if else here to only have the single HTML element

2020-11-17 15:25 UTC, dannewnsjump24 commented on tests/Feature/Store/Orders/OrderDetails/OrderDetailsPostControllerTest.php
> +        $this->markTestSkipped('TODO: Fix this flakey test.');
is there anyway we can fix this test?

2020-11-17 15:25 UTC, dannewnsjump24 commented on app/Contract/Repositories/InventoryContract.php
> +     * @return Inventory
these should have `null|` as they can return null or Inventory. is phpstan running on this project?

2020-11-17 15:43 UTC, SecondeJK commented on app/Contract/Repositories/InventoryContract.php
> +     * @return Inventory
I'll get this fixed, but in the meantime, I really don't know why phpstan isn't picking this up, or the IDE.

2020-11-17 16:20 UTC, SecondeJK commented on tests/Feature/Store/Orders/OrderDetails/OrderDetailsPostControllerTest.php
> +        $this->markTestSkipped('TODO: Fix this flakey test.');
Trying to debug this with a bash loop

2020-11-19 14:48 UTC, dannewnsjump24 approved these changes

2020-11-19 14:50 UTC, merged